---
- name: Install Apache on RHEL
  hosts: demo
  become: true

  tasks:
  - name: Install Apache
    ansible.builtin.yum:
      name: httpd
      state: present
  - name: Start Apache
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
  - name: Allow incoming traffic on port 80
    ansible.posix.firewalld:
      service: http
      state: enabled
      permanent: true
      immediate: true
